### ISSUE TITLE
Control page not responding when MQTT not connected

### ISSUE THREAD

**Issue by roguenorman** [dzungpv/mitsubishi2MQTT#1]
hey I noticed that when I am not connected to the HVAC and I try to go to the control page, it redirects me to the status page which is good. I then connect to the HVAC, but don't connect to MQTT and try to navigate to the control page but it just hangs there. When I am connected to MQTT the control page works as expected. 

So there seems to be an issue with the redirect to the status page when HVAC is connected but MQTT is not

I'm running the current master and not a release

**Comment by dzungpv** [comment]
Long time, I am not read it. It may cause by slow WiFi, you can waiting for 1 minute or update to powerful ESP32
