### ISSUE TITLE
Add Time zone option

### ISSUE THREAD

**Issue by dtalens** [dzungpv/mitsubishi2MQTT#15]
Hello,

The correct current time for my time zone (UTC+1) is not displayed on my devices as the code is set to Vietnam Standard Time. Consider including an option to indicate the time zone.
![image](https://github.com/dzungpv/mitsubishi2MQTT/assets/6631832/e3a2568b-6d94-4281-ace1-d8d752045ce6)

https://github.com/dzungpv/mitsubishi2MQTT/blob/88e3ea1cd3be448482e8caa16f38e25b446d8d6a/main/main.cpp#L3261

Merry Christmas,

**Comment by dzungpv** [comment]
OK, it is in my list, will be available soon.

**Comment by dzungpv** [comment]
@dtalens You can now change timezone in the Setup->Others via https://github.com/dzungpv/mitsubishi2MQTT/commit/c3e66da451009d307c16d5a0a3b473800149943a. Example you enter: CET-1CEST,M3.5.0,M10.5.0/3 for Madrid.
