### ISSUE TITLE
Reboot required every ~15 hours

### ISSUE THREAD

**Issue by lrgabriel** [dzungpv/mitsubishi2MQTT#23]
Hello again - thank you for looking!

I have three MSZ-GL12NAs with Wemos D1 Mini Clones running 2023.12.4, controlled from Home Assistant over MQTT.  This works great, except:

They all stop responding after being up for 15 hours, plus or minus 20 minutes.  All three of them do this, and it's very repeatable.

When they are offline, an MQTT browser shows mitsubishi2mqtt/hvac-backbedroom/**availability = offline**.  The webpage still responds fine, and the Status page shows green CONNECTED for both HVAC and MQTT Status.

Clicking REBOOT fixes it for another 15 hours.

Is there anything I can do to fix this, or help troubleshoot it further?

At the moment, I have a watchdog that calls http://xxx.xxx.xxx.xxx/?REBOOT= when the entity become available.

Thank you again!

**Comment by dzungpv** [comment]
I have 2 esp8266 Wemos D1 mini running latest version for more than 60 days without reboot, you can monitor uptime in the status page or in Home Assistant.
You problem may be the wifi signal or the ESPs itself. Esp8266 limit memory so change the way you monitor it like monitor offline state.
This is the screenshot, ESP8266 counter show negative when it overflow after 50 days.

![Untitled](https://github.com/dzungpv/mitsubishi2MQTT/assets/10563561/b8a27863-567f-469d-ae4d-a332709cf110)

**Comment by dzungpv** [comment]
But I am running old version, a guy push some code may fix the issue, you can download the snapshot here https://github.com/dzungpv/mitsubishi2MQTT/actions/runs/8261852251 update and test if it OK report back to me.

**Comment by dzungpv** [comment]
CI failed for PlatformIO, you can download it here https://github.com/dzungpv/mitsubishi2MQTT/actions/runs/8262169721

**Comment by dzungpv** [comment]
@lrgabriel I will close this issue, you can re-open it if still have problem.

**Comment by pzbitskiy** [comment]
I had a "similar" problem running without MQTT. Status page showed "free heap" when from 42% to 22% in an hour and the Control and Setup/Unit were not able to open. Other pages were OK, `/event` kept reporting events. I made a fix for my case in #29 but I suspect there is a memory leak somewhere, and as soon as you get 15h * 60 req/h =~ 900 requests it stops working similar to mine.
